pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/username/travel-booking-assistant.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo Build Successful'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                sudo cp -r * /var/www/html/
                '''
            }
        }
    }
}'
            }
        }

        stage('Build') {
            steps {
                sh 'echo Build Successful'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                sudo cp -r * /var/www/html/
                '''
            }
        }
    }
}
